title: The Brewery
email: info@thebrewery.se
description: "This is The Brewery's tech blog and collection of how-tos."
url: https://the-brewery.github.io
baseurl: 

markdown: kramdown
highlighter: pygments
permalinks: pretty
paginate: 5

exclude: [vendor]
