title: The Brewery
email: info@thebrewery.se
description: "This is The Brewery's tech blog and collection of how-tos."
url: http://tech.thebrewery.se
baseurl: 

markdown: kramdown
highlighter: rouge
permalinks: pretty
paginate: 5

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [vendor]
